# متغیر {#sec-variable}

برخی دستورات پایتون شامل مقادیری است که مجدداً درون برنامه، برنامه‌نویس
 به آن نیاز خواهد داشت. 
 بنابراین ما به عنوان برنامه‌نویس می‌بایست یک نام نمادین برای این مقادیر تعریف کنیم 
 که در وقت لازم با این نام تعریف شده، پایتون را متوجه استفاده از آن مقدار موردنظر 
 گردانیم. 
 واژه‌ای که برای این نام مخصوص استفاده می‌شود، 
 **Variable** 
  یا **متغیر** است:

```python
x = 6
print(x)
```
```output
6
```

```python
y = x * 7
print(y)
```
```output
42
```

در این مثال ساده، ما سعی کردیم به پایتون بگوییم در ابتدا برای مقدار `6`، برچسبی به نام 
`x`
در نظر بگیرد و سپس در دستور بعدی همین مقدار را با نام 
`x`
بازیابی کردیم. آنگاه آن را در `7` ضرب کرده و حاصل آن را در متغیر جدیدی با نام 
`y` 
ذخیره کردیم. 

دو خط مربوط به تابع 
`print`
مقادیر 
`x` 
و 
`y` 
صرفاً برای مشاهده مقادیر ذخیره شده در متغیرهای بکار رفته در پرانتز می‌باشد. 


::: {.callout-important}
کاراکترهای مجاز برای متغیرها به صورت `A-Z`, `a-z`, `0-9` و `_` است.
:::

::: {.callout-tip}

انواع متغیرها

```python
Variable_25 = "Salam" 
```

- `lowercase`

```python
thisisalowercase = "value" 
```

- `snake_case` 

```python
this_is_a_snake_case_variable = "value"
```

- `camelCase`

```python
thisIsACamelCaseVarible = "value"
```

- `PascalCase`

```python
ThisIsPascalCaseVariable = "value"
```

- `UPPERCASE`

```python
THISISAUPPERCASEVARIABLE = "value"
```

- `kebab-case`

```python
this-is-a-kebab-case-variable = "value"
```
```output
  File "<stdin>", line 1
    this-is-a-kebab-case-variable = "value"
         ^^
SyntaxError: invalid syntax
```

::: {.callout-important}
معمولا از ترکیب 
`UPPERCASE`
و
`kebab-case`
برای متغیرهای مسیر و فایل‌ها استفاده می‌شود.

```python
PATH_OR_FILE ="this-is-a-kebab-case-path/filename"
```
:::
:::


گرفتن ورودی از کاربر به صورت زیر است

```python
name = input("Enter your name: ")
print("Hello", name)
```
```output
Enter your name: Mohsen
Hello Mohsen
```

اگر ورودی عدد باشد باید توسط `input` در قالب عدد وارد شود.

```python
age = int(input("Enter your age: "))
print("You are", age, "years old.")
```
```output
Enter your age: 30
You are 30 years old.
```

## تمرین

::: {.callout-warning}
با استفاده از ورودی ([`input()`]{dir=ltr}) تمرین‌ها انجام شود.
:::

::: {.callout-caution title="نام و سن کاربر را نمایش دهد" icon="false" collapse="true"}

```python
name = input("نام خود را وارد کنید: ")

age = input("سن خود را وارد کنید: ")

print("نام:", name)
print("سن:", age)
```
:::

::: {.callout-caution title="پروژه" icon="false"}
به بخش @sec-project-calculator بروید و نگاه کنید کدام قسمت از کد را می‌توانید بفهید.
:::
